Issue: Add project governance document
pravega/community pull request #2
Opened 2021-04-23 15:27 UTC by fpj

* Summarizes project mission
* Describes project structure
* Describes decision making
* Applies to all repositories across the Pravega org

Signed-off-by: Flavio Junqueira (fpj) <fpj@apache.org>

2021-04-23 15:31 UTC, fpj commented on governance.md
> +The following are email lists available to the project:
I assumed mailing lists for communication. We need to decide whether we want to stick to it. Part of the reason for suggesting it is that email tends to be archived so we can have the communication history stored indefinitely as opposed to  other ways to communicate (e.g., Slack), which I'm not sure we can guarantee archival.

2021-04-23 15:32 UTC, fpj commented on governance.md
> +## Decision making
A good chunk of this section derives from the Apache ZooKeeper bylaws.

2021-04-23 15:39 UTC, derekm commented on governance.md
> +The following are email lists available to the project:
I agree that email is best, especially for lists where official decisions will be made. Unofficial traffic, like users and dev traffic, may split between several forums, including the email lists. But it makes sense that maintainers and steering committee traffic should mostly occur on the mailing lists.

2021-04-27 19:23 UTC, derekm commented on governance.md
> +If a Steering Committee member wants to propose Joe as a new committer and wants to discuss Joe's merits before calling a vote, the member can start an email thread in the private list with title `[D
Sentence trails off, "Once it..."

2021-05-04 15:56 UTC, derekm requested changes

2021-05-04 15:56 UTC, derekm commented on governance.md
> +The project comprises two main groups of contributors:
We need to make explicit which group maps to CNCF's concept of "maintainers/owners." The only governance structure required by CNCF is the "maintainers" mailing list, whose members will be listed at <https://maintainers.cncf.io/>. Maintainers are those who will have access to CNCF Service Desk and who will see official communications from CNCF to the project via the maintainers mailing list.

2021-05-26 18:00 UTC, derekm commented on governance.md
> +- cncf-pravega-private@lists.cncf.io : this is a list reserved to the members of the steering committee. It should be used only for private topics, such as discussion on new committeers and voting of
I believe this will be `cncf-pravega-maintainers@lists.cncf.io`, according to CNCF conventions.

2021-05-31 21:41 UTC, fpj commented on governance.md
> +- cncf-pravega-private@lists.cncf.io : this is a list reserved to the members of the steering committee. It should be used only for private topics, such as discussion on new committeers and voting of
Nowhere in the document we are referring to maintainers. Are you suggesting implicitly that we say that the steering committee and maintainers are the same?

2021-05-31 21:42 UTC, fpj commented on governance.md
> +The project comprises two main groups of contributors:
Should we make the steering committee members maintainers of the project to comply with CNCF roles and terminology?

2021-06-01 22:06 UTC, derekm commented on governance.md
> +- cncf-pravega-private@lists.cncf.io : this is a list reserved to the members of the steering committee. It should be used only for private topics, such as discussion on new committeers and voting of
The email traffic on `cncf-pravega-maintainers` will be private, so it will serve the same role as `cncf-pravega-private`, but named following CNCF conventions. Cf., https://lists.cncf.io/g/cncf-keda-maintainers

Perhaps elsewhere we state the Steering Committee==CNCF Project Maintainers relationship more explicitly.

2021-06-04 11:21 UTC, derekm commented on governance.md
> +Code change | Lazy Approval | Committer | Public | 1
In what forum are public votes expected to be taken? cncf-pravega-dev mailing list?

2021-06-04 11:25 UTC, derekm commented on governance.md
> +- cncf-pravega-private@lists.cncf.io : this is a list reserved to the members of the steering committee. It should be used only for private topics, such as discussion on new committers and voting of
`cncf-pravega-maintainers@lists.cncf.io` was created yesterday.

Do we also need a `cncf-pravega-committers@lists.cncf.io` list? Would committers list be public or private?

What list do public votes occur on?

2021-06-04 11:33 UTC, derekm commented on governance.md
> +Create a new repository | 2/3 Majority | Steering Committee | Public | 7
I think any pravega org member can create new repos at present: https://github.com/organizations/pravega/settings/member_privileges

I'm not sure if creation of public repos can be restricted.

2021-06-04 11:36 UTC, derekm commented on governance.md
> +The initial vote message must contain the deadline for contributors to vote. Once the deadline has passed, the initiator can decide to conclude or extend it as needed. One reason for extending is not
Is there a minimum deadline duration or a suggested/typical/recommended deadline duration?

2021-06-04 11:39 UTC, derekm commented on governance.md
> +The initial vote message must contain the deadline for contributors to vote. Once the deadline has passed, the initiator can decide to conclude or extend it as needed. One reason for extending is not
Minimum deadline durations are set out in the Actions table above. Should this be pointed out explicitly here?

2021-06-04 11:40 UTC, derekm commented on governance.md
> +Code change | Lazy Approval | Committer | Public | 1
What is a "code change" action? Are PRs expected to have mailing list vote threads?

2021-06-04 16:31 UTC, fpj commented on governance.md
> +Create a new repository | 2/3 Majority | Steering Committee | Public | 7
If we can't enforce, then we will have to manually remove in the case of misbehavior.

2021-06-04 16:33 UTC, fpj commented on governance.md
> +The initial vote message must contain the deadline for contributors to vote. Once the deadline has passed, the initiator can decide to conclude or extend it as needed. One reason for extending is not
Done

2021-06-04 16:34 UTC, fpj commented on governance.md
> +- cncf-pravega-private@lists.cncf.io : this is a list reserved to the members of the steering committee. It should be used only for private topics, such as discussion on new committers and voting of
Are we going to to use `maintainers` instead of `private`? It is not clear to me that such a list has restricted visibility and access.

2021-06-04 16:34 UTC, fpj commented on governance.md
> +Code change | Lazy Approval | Committer | Public | 1
I have clarified below, see if it is sufficient.

2021-06-04 16:44 UTC, derekm commented on governance.md
> +- cncf-pravega-private@lists.cncf.io : this is a list reserved to the members of the steering committee. It should be used only for private topics, such as discussion on new committers and voting of
I think the `maintainers` lists are as private as `private` would be. I was originally mistaken that the messages were public. I'll see if I can get into a maintainers list I'm not in, but I don't think I can.

2021-06-04 16:59 UTC, fpj commented on governance.md
> +- cncf-pravega-private@lists.cncf.io : this is a list reserved to the members of the steering committee. It should be used only for private topics, such as discussion on new committers and voting of
If you look here:

https://lists.cncf.io/g/cncf-pravega-maintainers

it says:

> Subscriptions to this group do not require approval from the moderators.

I interpret that as anyone being able to join.

2021-06-04 17:00 UTC, derekm commented on governance.md
> +Code change (Pull Request) | Lazy Approval | Committer | Public | 1
Approval type of "Lazy Approval" calls for one of two fallback mechanisms in case of a -1 veto.

Action types table should indicate which fallback is used for actions having "Lazy Approval."

2021-06-04 17:57 UTC, derekm commented on governance.md
> +- cncf-pravega-private@lists.cncf.io : this is a list reserved to the members of the steering committee. It should be used only for private topics, such as discussion on new committers and voting of
Amye has fixed the permissions on our mailing list.

2021-06-04 17:59 UTC, derekm commented on governance.md
> +- cncf-pravega-user@lists.cncf.io : this list is for users to ask questions about how to use Pravega software. It is common across all teams.
List is `cncf-pravega-users@lists.cncf.io`

2021-06-04 18:00 UTC, fpj commented on governance.md
> +- cncf-pravega-user@lists.cncf.io : this list is for users to ask questions about how to use Pravega software. It is common across all teams.
I intentionally used singular, it is the user list.

2021-06-04 18:03 UTC, derekm approved these changes
I think we caught everything (or most everything).

2021-06-04 18:05 UTC, merged